### PR TITLE
feedback changes

### PR DESCRIPTION
**Pull request by dharmykoya**
#### What does this PR do?
Changes to frontend and backend of the banka app
##### UI
 - font color in the UI
 - page positioning in the UI
 - javascript in the UI should be written with ES6 standard
 - add status badge to the profile pages.
##### Server
 - rename api folder to server folder
 - add unwanted files to gitignore
 - change test to check for values and not keys
 - make password stronger
 - correct errors on readme file
 - check for the three types of user only
#### How should this be manually tested?
- after merging visit the UI [here](https://dharmykoya.github.io/banka/UI)
- to test back end follow the instructions below
 ## Installation
1. Ensure you have Node.js and npm installed

2. Clone this repo
```bash
$ git clone https://github.com/dharmykoya/book_a_meal.git
```
3. Install Dependencies
```bash
npm install
```
4. Run Test
```bash
npm run test
```
#### Any background context you want to provide?
Javascript, Nodejs, Html and CSS
#### What are the relevant pivotal tracker stories?
NA
#### Screenshots (if appropriate)
I changed the color of the navbar items and brought the items closer
index

The bank users tab is opened on page load
admin_dashboard

I removed the table on top of the tabs as it was not appealing
all_accounts

I redirect users to this page on signup
create_account

I added the status badge and the action buttons to know it click able
staff_dashboard

I positioned the items to align together
transaction

#### Questions:
NA

### CODE REVIEW

**Comment by samdiano** [comment]
rename the folder to `server`
and add screenshots of the UI update

**Comment by samdiano** [comment]
your coverage decreased. Have you looked into it?

**Comment by dharmykoya** [comment]
I will look into the coverage now, It's now checking my frontend files and I will get back on the UI

**Comment by dharmykoya** [comment]
I have done the final commit

**Review by samdiano — APPROVED** [review]

**Pull request merged**
